allowBuilds:
  '@tailwindcss/oxide': set this to true or false
  '@vercel/speed-insights': set this to true or false
  contentlayer2: set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
